#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server

if [ $# -lt 4 ]
then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1

fi

file_path=$1
ip=$2
userame=$3
path_to_ssh=$4

scp -o "StrictHostKeyChecking=no" -i "$4" "$1" "$3@$2:~/"
