#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

apt-get -y update
apt-get -y install nginx
#Custom html msg
echo "Hello World!" | tee /var/www/html/index.html
#redirections
str_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\ permanent;"
sudo sed -i "s/server_name _;/$str_replacement/" /etc/nginx/sites-enabled/default

#custom error msg
str_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"

#cusstom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "s/listen 80 default_server;/$str_replacement/" /etc/nginx/sites-enabled/default
sed -i '/server_name _;/ a\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n' /etc/nginx/sites-available/default
sudo nginx -t
service nginx restart
