#!/usr/bin/env bash
#Custom HTTP response header

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i "/server_name _/a add_header X-Served-By \$HOSTNAME;" /etc/nginx/sites-enabled/default

sudo nginx -t

sudo service nginx restart
