#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with 2 iteration & Displays "I am invincible!!!" 


while true
do
  echo "To infinity and beyond"
  sleep 2
  trap 'echo "I am invincible"' SIGTERM 
done
