#!/usr/bin/env bash
# Displays "To infinity and beyond" indefinitely with 2 iteration & Displays "I am invincible!

trap 'echo "I am invincible!!!"' SIGTERM
while :
do
    echo "To infinity and beyond"
    sleep 2
done
