#!/bin/bash env
#A script that sets firewall rules on my web-01.

sudo apt-get update

#install ufw 
sudo apt-get install ufw

#Default policies
sudo ufw default deny incoming
sudo ufw default allow outgoing

#allow communication on specific ports
sudo ufw allow 22/tcp
sudo ufw allow 443/tcp
sudo ufw allow 80/tcp

#enable ufw
sudo ufw enable
